### ISSUE TITLE
Doing Image.save_bytes() prints "guess" in my console

### ISSUE THREAD

**Issue by SnivyLlama** [Daggy1234/polaroid#6]
Title says it all. Whenever I run `save_bytes()` on an `Image` object, it just prints "guess" in my console. Why is that?

**Comment by daggy1234** [comment]
Default kwarg for save_bytes is `guess` which means polaroid will intelligently predict sand save image based on format. You can override the behavior. There is a debug print for printing the format will fix

**Comment by daggy1234** [comment]
Closed in new commit
